version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf      
      - ./data/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8070:80"
      - "8443:443"
    networks:
      - webproxy

  riotweb:
    image: bubuntux/riot-web:latest
    hostname: riotweb
    restart: unless-stopped
    volumes:
      - ./data/app/config.json:/etc/riot-web/config.json:ro
    networks:
      - webproxy

  synapse:
    image: matrixdotorg/synapse:latest
    hostname: synapse
    restart: unless-stopped
    ports:
      - 8008:8008
      - 8009:8009   
    environment:
      - SYNAPSE_SERVER_NAME=${FQDN}
      - POSTGRES_DB=postgres
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SYNAPSE_NO_TLS=1
      - SYNAPSE_MAX_UPLOAD_SIZE=100M
    volumes:
      - ./data/app:/data
    depends_on:
      - db
    networks:
      - webproxy

  db:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - webproxy
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - webproxy

networks:
  webproxy:
